export const WORDS: Record<"easy" | "medium" | "hard", string[]> = {
  easy: [
    "sun", "cat", "dog", "tree", "house", "car", "ball", "fish", "star", "moon",
    "hat", "shoe", "book", "cup", "door", "bed", "bird", "rain", "eye", "hand",
    "clock", "phone", "chair", "table", "lamp", "boat", "kite", "snow", "fire", "key",
    "apple", "baby", "cloud", "drum", "egg", "flag", "gift", "heart", "ice", "jar",
    "king", "leaf", "mouse", "nose", "owl", "pig", "queen", "ring", "sock", "tent",
    "train", "wave", "smile", "cake", "coin", "duck", "fork", "ghost", "hill", "jump",
    "kiss", "lion", "milk", "nest", "ocean", "pizza", "robot", "snake", "tooth", "wheel",
    "banana", "candle", "flower", "guitar", "ladder", "mirror", "pencil", "rabbit", "spider", "window",
    "button", "cheese", "cookie", "dragon", "feather", "hammer", "lemon", "pillow", "rocket", "turtle",
    "anchor", "bridge", "cherry", "donut", "garden", "island", "jacket", "parrot", "zigzag", "puzzle",
  ],
  medium: [
    "airplane", "backpack", "calendar", "diamond", "elephant", "fountain", "giraffe", "homework", "iceberg", "jellyfish",
    "kangaroo", "lobster", "mushroom", "necklace", "orchestra", "penguin", "quicksand", "rainbow", "sandwich", "telescope",
    "umbrella", "volcano", "windmill", "xylophone", "treasure", "passport", "aquarium", "bathrobe", "campfire", "dominoes",
    "earphone", "firework", "goldfish", "horseshoe", "inventor", "jigsaw", "keyboard", "lifeguard", "magnifier", "notebook",
    "Olympics", "parachute", "recycle", "scarecrow", "tightrope", "unicycle", "vineyard", "werewolf", "yearbook", "zeppelin",
    "blizzard", "catapult", "dynamite", "espresso", "flamingo", "gladiator", "hedgehog", "illusion", "jackpot", "kombucha",
    "lantern", "moustache", "navigator", "ostrich", "platypus", "quarters", "roadblock", "staircase", "trapeze", "uniform",
    "vampire", "wallpaper", "asteroid", "bulldozer", "crossbow", "daffodil", "excavator", "freeway", "gargoyle", "hibiscus",
    "igloo", "junkyard", "kayak", "lemonade", "marathon", "nightclub", "obstacle", "porcupine", "rattlesnake", "skydiving",
    "treadmill", "underwear", "ventriloquist", "whirlpool", "armadillo", "boomerang", "chandelier", "dragonfly", "evergreen", "fireplace",
  ],
  hard: [
    "abstract", "bankruptcy", "camouflage", "déjà vu", "endangered", "foolproof", "guillotine", "hypothermia", "immigration", "jurisdiction",
    "kaleidoscope", "labyrinth", "metabolism", "nostalgia", "obligation", "photosynthesis", "quarantine", "renaissance", "surveillance", "turbulence",
    "unanimous", "ventriloquism", "wanderlust", "claustrophobia", "bureaucracy", "archaeology", "blacksmith", "conspiracy", "diplomacy", "ecosystem",
    "franchise", "generation gap", "hibernation", "inflation", "jury duty", "knowledge", "legislation", "meditation", "negotiation", "opportunity",
    "philosophy", "revolution", "superstition", "time zone", "unemployment", "vaccination", "wavelength", "boundaries", "civilization", "dehydration",
    "electricity", "frustration", "gravity", "hieroglyphics", "instinct", "journalism", "keynote", "longitude", "microscopic", "networking",
    "observatory", "perspective", "quarterback", "recyclable", "sportsmanship", "teleportation", "ultraviolet", "vocabulary", "wilderness", "anonymous",
    "blueprint", "conscience", "distraction", "evolution", "flashback", "globalization", "hemisphere", "independence", "jeopardize", "knuckleball",
    "liabilities", "monologue", "nonprofit", "overqualified", "plagiarism", "quadrilateral", "rehabilitation", "stereotype", "tranquility", "underestimate",
    "versatile", "weightlessness", "atmosphere", "brainwash", "choreography", "documentary", "encryption", "fingerprint", "greenhouse", "immigration",
  ],
};
